-- ============================================================
-- CREATE TABLE cyber_abilities
-- ============================================================

CREATE TABLE public.cyber_abilities (
  id           uuid        NOT NULL DEFAULT gen_random_uuid(),
  name         text        NOT NULL,
  description  text        NULL,
  ability_type text        NULL,
  source       text        NULL,
  gm_notes     text        NULL,
  cost         text        NULL,
  img_url      text        NULL,
  tags         jsonb       NULL DEFAULT '[]'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cyber_abilities_pkey PRIMARY KEY (id)
);

-- ============================================================
-- INSERT (40 rows, original UUIDs preserved)
-- ============================================================

INSERT INTO public.cyber_abilities
  (id, name, description, ability_type, source, gm_notes, cost, img_url, tags)
VALUES
  ('139cc92b-70cd-416c-bf61-cf9f833eef94', 'Brute Force', 'Discard 1 card from hand (any). Play an Attack Card. If this attack hits, its value (damage/effectiveness) is Doubled.', 'Active', 'Mercenary, Soldier, Juggernaut', 'Brutal efficiency moment. Mercenary uses resources to deal one decisive blow intended to end the problem.', '1 card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/01/karta.png', '["Combat", "Power", "Sacrifice"]'::jsonb),
  ('1aa5844c-9342-4455-8383-2c791174ef1e', 'Fiber-Optic Lure', 'Hypnotizes an NPC using pulsing lights from tattoos and hair.', 'Active', 'Neon-Nymph, Psychic, Android', 'Victim stares at the neon glow.', '1 Mental Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-27.svg', '["Light", "Social", "Distraction"]'::jsonb),
  ('2975d74a-00df-4f1e-bd81-092dbee2598e', 'Master Calibration', 'Every item card (weapon/tool) you use has its success value doubled.', 'Passive', 'Techno-Dwarf, Augmented Human, Mercenary', 'The character knows every screw and bolt of their equipment.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-11.svg', '["Craft", "Buff", "Tool"]'::jsonb),
  ('30bae120-3596-4695-b6b8-cbc53a77da20', 'Entropy Gaze', 'Forces an enemy card to lose all its tags for one turn due to void interference.', 'Active', 'Void-Touched, Psychic, Spirit', 'Eyes turn into pitch-black voids.', '1 Mental Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-13.svg', '["Void", "Debuff", "Anti-Magic"]'::jsonb),
  ('3493536f-dbe1-482e-bb8d-049556939418', 'Alpha Command', 'Force a weaker NPC to perform a simple task through sheer dominant presence.', 'Active', 'Lion, Human, Psychic', 'Voice resonates with terrifying power.', '1 Mental Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-19.svg', '["Presence", "Social", "Intimidation"]'::jsonb),
  ('48334bc3-35e8-4458-92df-907380568b9e', 'Kinetic Roar', 'Pushes back all enemies in short range, stunning them with a sonic shockwave.', 'Active', 'Lion, Bear, Mutant, Steam-Automaton', 'Describe cracking screens and bleeding ears.', '1 Physical Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-20.svg', '["Sonic", "Crowd_Control", "Power"]'::jsonb),
  ('58e890d3-7d5d-4fcf-a7cc-70ee0645bc2c', 'Shadow Slip', 'Exit combat without an escape roll, leaving behind a trail of dark data particles.', 'Active', 'Void-Touched, Spirit, Raven-Shifter, Hacker', 'The character dissolves into shadows.', '1 Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-14.svg', '["Void", "Stealth", "Escape"]'::jsonb),
  ('69a9b1e9-7288-4ac8-be81-9211d8b25013', 'Telepathic Link', 'Once per round, when ally plays test card with unsatisfactory result, Psychic may give them card from hand. Ally uses it instead or adds to theirs.', 'Passive', 'Psychic, Neural-Cloud, Support', 'Shared consciousness. AI: Paralysis/hallucination in combat, precise hints in dialogue.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/01/karta.png', '["Support", "Psychic", "Teamwork"]'::jsonb),
  ('6a79e0f2-9387-45fd-b38d-2f66264d95c3', 'Clipping', 'Walk through a locked door or obstacle by momentarily glitching out of reality.', 'Active', 'Glitched One, Spirit, Ethereal Elf, Neural-Cloud', 'The character flickers and clips.', '1 High Value Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-23.svg', '["Glitch", "Movement", "Abstract"]'::jsonb),
  ('6ccf31a5-6783-41d5-afba-945d0de51854', 'Battle Hardened', 'The Mercenary ignores negative effects from Panic or Pressure cards that force random discard. Chooses which card to discard instead.', 'Passive', 'Mercenary, Soldier, Veteran', 'In card systems, losing control of hand is painful. Mercenary retains control - player decides sacrifice.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/01/karta.png', '["Defense", "Discipline", "Control"]'::jsonb),
  ('729b8657-f071-448c-9c14-9924ffbbb4cf', 'Pressure Release', 'Releases a burst of steam that blinds enemies.', 'Active', 'Steam-Automaton, Echo of Industry, Mercenary', 'Loud hiss and white cloud.', '1 Physical Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-37.svg', '["Clockwork", "Steam", "Escape"]'::jsonb),
  ('72e57277-ee45-4e1b-a5fb-8c47d4c1a410', 'Biomodification', 'Instantly change your weapon''s tag (e.g., Blunt to Piercing) by reshaping bone.', 'Active', 'Flesh-Weaver, Mutant, Abomination', 'The sound of cracking bones.', '1 Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-21.svg', '["Bio-Tech", "Adaptation", "Utility"]'::jsonb),
  ('78dff456-7afa-4d68-912f-f29203943db3', 'Hard-Light Construct', 'Create a temporary simple object (key, blade) out of pure light.', 'Active', 'Neural-Cloud, Ethereal Elf, Hacker', 'Pixels solidify in hand.', '1 Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-35.svg', '["Digital", "Manifestation", "Utility"]'::jsonb),
  ('89c8bb93-bd4c-49a9-923e-0325425817fd', 'Versatility', 'During character creation, choose 1 additional Feat Card from any class deck normally inaccessible.', 'Passive', 'Human, Augmented Human, Android', 'Allows hybrid builds like Warrior with Rogue trick.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/01/karta.png', '["Build", "Utility", "Hybrid"]'::jsonb),
  ('8e5e51c9-5a4d-4a41-91c7-fd02c81e9e74', 'Skystrike', 'An attack from above ignores the target''s armor due to momentum and precision.', 'Active', 'Raven-Shifter, Ethereal Elf, Assassin', 'A shadow falling from the sky.', '1 Physical Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-18.svg', '["Aerial", "Combat", "Armor_Pierce"]'::jsonb),
  ('92b84ca4-e30f-4bb3-b45a-e21461504235', 'Reactive Evolution', 'After taking elemental DMG, gain resistance to that type until the end of the scene.', 'Passive', 'Mutant, Abomination, Flesh-Weaver', 'Skin hardens in response to stress.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-25.svg', '["Evolution", "Defense", "Passive"]'::jsonb),
  ('99be94da-8533-43d8-88d7-7e28fd305cef', 'Machine Haunting', 'Take control of a vehicle or turret by infusing it with spectral essence.', 'Active', 'Echo of Industry, Spirit, Hacker, Android', 'Machine moves organically.', '2 Cards', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-32.svg', '["Pollution", "Control", "Machine"]'::jsonb),
  ('9b700fb6-8ae8-422f-889d-35c1b71a756c', 'Smog Screen', 'Creates a cloud of thick, toxic smoke that obscures vision.', 'Active', 'Echo of Industry, Steam-Automaton, Mutant', 'Smell of burnt rubber and ozone.', '1 Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-31.svg', '["Pollution", "Cloud", "Stealth"]'::jsonb),
  ('9e895d5c-b9a0-4219-ab6c-083773378c28', 'Neural Tracking', 'See digital trails of your target through walls (thermal/data layers). Bonus to tracking.', 'Passive', 'Cyber-Wolf, Beastmen, Mutant, Raven-Shifter', 'Describe the world as a grid of vectors.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-15.svg', '["Sensors", "Hunting", "Information"]'::jsonb),
  ('a2a1d305-4fd9-4170-8592-0edab254d706', 'Second Wind', 'Once per session, when drawing Failure Card, discard it and draw new card. Must accept second result.', 'Active', 'Human, Augmented Human, Hero', 'Sudden burst of determination or adrenaline surge.', 'Once per session', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/01/karta.png', '["Luck", "Survival", "Heroic"]'::jsonb),
  ('a37ecdec-d32d-42ca-9abc-a34c85b4de1c', 'Suture Touch', 'Heals an ally (2 HP), but requires discarding a Physical card (using your own blood).', 'Active', 'Flesh-Weaver, Mutant, Psychic', 'Wound closes unnaturally.', '1 Physical Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-22.svg', '["Bio-Tech", "Heal", "Blood_Cost"]'::jsonb),
  ('a508ef94-912a-45de-b49b-972cb2306944', 'Logic Loop', 'Trap an enemy AI in a decision loop.', 'Active', 'Android, Neural-Cloud, Psychic, Hacker', 'Systems freeze analyzing paradox.', '1 Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-40.svg', '["Logic", "Mental", "Stun"]'::jsonb),
  ('a5614980-68d8-4b73-acd6-4315ea6f1f97', 'Corrupted Signal', 'Any enemy attacking you must discard a random card due to digital noise.', 'Passive', 'Glitched One, Android, Neural-Cloud', 'Visual sync error makes it painful to look.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-24.svg', '["Glitch", "Defense", "Feedback"]'::jsonb),
  ('b10a4d9f-b4ea-4614-86ed-ec5d227b9a0f', 'Unstable Limb', 'An attack with increased range that might damage the mutant if the test fails.', 'Active', 'Mutant, Abomination, Glitched One', 'The limb extends in a grotesque fashion.', '1 Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-26.svg', '["Evolution", "Combat", "Unpredictable"]'::jsonb),
  ('b19648c6-3d62-4ba8-a735-3022d76a5a71', 'Vow of Silence', 'Prevents spellcasting and radio usage in your vicinity.', 'Active', 'Guardian Wraith, Spirit, Assassin', 'Air grows heavy and signals go dead.', '1 High Value Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-30.svg', '["Spirit", "Silence", "Aura"]'::jsonb),
  ('b42942ff-ca57-42cb-9cbe-b01cc0fd8117', 'Phase Out', 'Become invisible to digital sensors and cameras for 3 turns.', 'Active', 'Ethereal Elf, Spirit, Glitched One, Hacker', 'ID disappears from the network.', '1 Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-34.svg', '["Code", "Stealth", "Invisibility"]'::jsonb),
  ('b69ef6d5-706d-42f0-b795-7afc2fcba3da', 'Heavy Frame', 'You cannot be pushed back or knocked down. Gain a bonus to Strength tests in melee.', 'Passive', 'Techno-Dwarf, Steam-Automaton, Bear, Lion, Mercenary', 'Treat the character as an immovable object.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-12.svg', '["Stability", "Strength", "Passive"]'::jsonb),
  ('b992e047-c80a-481c-b8fc-e7aa1f904fe8', 'Spectral Aegis', 'Create a shield around an ally that completely blocks the next attack.', 'Active', 'Guardian Wraith, Spirit, Psychic', 'A ghostly hand catches the bullet.', '1 Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-29.svg', '["Protection", "Spirit", "Defense"]'::jsonb),
  ('c8cea20a-2acc-4542-94fc-2edd8599fe54', 'Circuit Jump', 'Teleport between electrical devices (e.g., street lamp to terminal).', 'Active', 'Neon-Nymph, Ethereal Elf, Spirit, Hacker', 'Turns into a pure electrical pulse.', '1 Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-28.svg', '["Electric", "Movement", "Hacking"]'::jsonb),
  ('ca29574d-5735-4005-850a-4abdf3dc08c7', 'Bloodsurge', 'If damaged in current scene, discard any card to draw Pure Aggression Card (high-value attack) and play immediately.', 'Active', 'Beastmen, Lion, Mutant, Berserker', 'Pain turns into fury. Character executes devastating attack.', '1 card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/01/karta.png', '["Combat", "Rage", "Risk_Reward"]'::jsonb),
  ('cbe2171f-2b63-4e46-a777-af3bc3257569', 'Iron Grip', 'Prevents an enemy from breaking free from a grapple.', 'Active', 'Steam-Automaton, Bear, Lion, Mercenary', 'Hydraulics lock in place.', '1 Physical Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-38.svg', '["Clockwork", "Strength", "Control"]'::jsonb),
  ('d06f1f29-75f4-4db2-b7b7-fc6524d97e37', 'Server Migration', 'Upon reaching 0 HP, consciousness transfers to the nearest terminal.', 'Passive', 'Neural-Cloud, Android, Glitched One', 'Body shuts down, voice from speakers.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-36.svg', '["Digital", "Resurrection", "Passive"]'::jsonb),
  ('d67bf825-02ec-40e6-9a8c-bdd68c074ce7', 'Data Mimicry', 'Intercept and listen to any radio or digital communication channel in the area.', 'Active', 'Raven-Shifter, Android, Hacker, Psychic', 'The ravens collect data packets.', '1 Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-17.svg', '["Spy", "Communication", "Intel"]'::jsonb),
  ('ebb39841-2239-4e7c-a733-bbd01d627bde', 'Pack Protocol', 'If an ally is in the same location, your attack gains the Critical tag.', 'Passive', 'Cyber-Wolf, Lion, Mercenary, Human', 'Coordinated strike through a shared pack link.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-16.svg', '["Tactics", "Combat", "Synergy"]'::jsonb),
  ('ee8e76e8-311b-4c4b-b2a8-3811fa3aff9e', 'High-Freq Precision', 'Your next test gains Advantage by predicting the future.', 'Active', 'Ethereal Elf, Neural-Cloud, Hacker', 'Time slows down, revealing trajectories.', '1 Mental Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-33.svg', '["Code", "Precision", "Buff"]'::jsonb),
  ('f832df97-b72e-4f89-b8a9-aff459b3043c', 'Deep Fake Emotions', 'Perfectly mimic the voice and behavior of any NPC.', 'Active', 'Android, Neural-Cloud, Psychic, Human', 'Synthesizer and motors at 100%.', '1 Mental Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-39.svg', '["Mimicry", "Social", "Infiltration"]'::jsonb),
  ('f913787a-8c01-45ee-84c0-d1b610c7574e', 'Feral Senses', 'Always play Perception and Survival test cards with Advantage. Draw 2 cards, choose better one.', 'Passive', 'Beastmen, Cyber-Wolf, Raven-Shifter, Mutant', 'Character has heightened senses, dominates exploration.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/01/karta.png', '["Sensors", "Exploration", "Passive"]'::jsonb),
  ('f97bf178-9c09-4266-8d2d-fdb2f1a869ce', 'Overclocked Neural Link', 'Boosts reflexes (draw an extra card), but deals 1 DMG to the user due to neural overheating.', 'Active', 'Augmented Human, Android, Neural-Cloud, Hacker', 'Describe smoke rising from the skin.', '1 HP', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-9.svg', '["Cyberware", "Risk_Reward", "Speed"]'::jsonb),
  ('fbe0da2e-e0ce-4b8b-9ecc-9f8433c215f5', 'Subdermal Plating', 'Ignore the first low-value attack in every combat encounter thanks to hidden reinforcements.', 'Passive', 'Augmented Human, Android, Steam-Automaton, Mercenary', 'Bullets ricochet with a metallic clang.', NULL, 'https://cyber.nieodparady.pl/wp-content/uploads/2026/02/ability-10.svg', '["Cyberware", "Defense", "Passive"]'::jsonb),
  ('fe290bea-9aea-4a5f-9b09-322d3ee65772', 'Mind Hack', 'Discard 1 Mental card. In Combat: Opponent forgets turn or attacks chosen enemy. In Dialogue: Peek top 3 Narrator Deck cards, rearrange order.', 'Active', 'Psychic, Hacker, Android', 'Momentary paralysis or hallucination. Gives precise hint in dialogue.', '1 Mental Card', 'https://cyber.nieodparady.pl/wp-content/uploads/2026/01/karta.png', '["Hack", "Mental", "Control"]'::jsonb);
